AVG_LAST_5_SCORES = "avgLast5Scores"
AVG_LAST_5_SCORES_AGAINST = "avgLast5ScoresAgainst"
AVG_LAST_5_BPS = "avgLast5Bps"
AVG_LAST_5_BPS_AGAINST = "avgLast5BpsAgainst"

HOME_TEAM_CODE = "team1Code"
AWAY_TEAM_CODE = "team2Code"
MONTH_CODE = "monthCode"
VENUE_CODE = "venueCode"
DAY_CODE = "dayCode"
REFEREE_CODE = "refereeCode"
SEASON_CODE = "seasonCode"
TARGET_CODE = "targetCode"
