AVG_HOME_LAST_5_SCORES = "avgHomeLast5Scores"
AVG_HOME_LAST_5_SCORES_AGAINST = "avgHomeLast5ScoresAgainst"

HOME_TEAM_CODE = "homeTeamCode"
AWAY_TEAM_CODE = "awayTeamCode"
MONTH_CODE = "monthCode"
VENUE_CODE = "venueCode"
DAY_CODE = "dayCode"
REFEREE_CODE = "refereeCode"
SEASON_CODE = "seasonCode"
TARGET_CODE = "targetCode"
