AVG_LAST_5_SCORES = "avgLast5Scores"
AVG_LAST_5_SCORES_AGAINST = "avgLast5ScoresAgainst"
AVG_LAST_5_BPS = "avgLast5Bps"
AVG_LAST_5_BPS_AGAINST = "avgLast5BpsAgainst"

AVG_LAST_5_TRIES = "avgLast5Tries"
AVG_LAST_5_CONVERSIONS = "avgLast5Conversions"
AVG_LAST_5_PENALTIES = "avgLast5Penalties"
AVG_LAST_5_DROP_GOALS = "avgLast5DropGoals"
AVG_LAST_5_TRIES_AGAINST = "avgLast5TriesAgainst"
AVG_LAST_5_CONVERSIONS_AGAINST = "avgLast5ConversionsAgainst"
AVG_LAST_5_PENALTIES_AGAINST = "avgLast5PenaltiesAgainst"
AVG_LAST_5_DROP_GOALS_AGAINST = "avgLast5DropGoalsAgainst"

HOME_TEAM_CODE = "team1Code"
AWAY_TEAM_CODE = "team2Code"
MONTH_CODE = "monthCode"
VENUE_CODE = "venueCode"
DAY_CODE = "dayCode"
REFEREE_CODE = "refereeCode"
SEASON_CODE = "seasonCode"
TARGET_CODE = "targetCode"
