AVG_LAST_5_SCORES_TEAM1 = "avgLast5ScoresTeam1"
AVG_LAST_5_SCORES_AGAINST_TEAM1 = "avgLast5ScoresAgainstTeam1"
AVG_LAST_5_BPS_TEAM1 = "avgLast5BpsTeam1"
AVG_LAST_5_BPS_AGAINST_TEAM1 = "avgLast5BpsAgainstTeam1"

AVG_LAST_5_SCORES_TEAM2 = "avgLast5ScoresTeam2"
AVG_LAST_5_SCORES_AGAINST_TEAM2 = "avgLast5ScoresAgainstTeam2"
AVG_LAST_5_BPS_TEAM2 = "avgLast5BpsTeam2"
AVG_LAST_5_BPS_AGAINST_TEAM2 = "avgLast5BpsAgainstTeam2"

AVG_LAST_5_TRIES_TEAM1 = "avgLast5TriesTeam1"
AVG_LAST_5_CONVERSIONS_TEAM1 = "avgLast5ConversionsTeam1"
AVG_LAST_5_PENALTIES_TEAM1 = "avgLast5PenaltiesTeam1"
AVG_LAST_5_DROP_GOALS_TEAM1 = "avgLast5DropGoalsTeam1"
AVG_LAST_5_TRIES_AGAINST_TEAM1 = "avgLast5TriesAgainstTeam1"
AVG_LAST_5_CONVERSIONS_AGAINST_TEAM1 = "avgLast5ConversionsAgainstTeam1"
AVG_LAST_5_PENALTIES_AGAINST_TEAM1 = "avgLast5PenaltiesAgainstTeam1"
AVG_LAST_5_DROP_GOALS_AGAINST_TEAM1 = "avgLast5DropGoalsAgainstTeam1"

AVG_LAST_5_TRIES_TEAM2 = "avgLast5TriesTeam2"
AVG_LAST_5_CONVERSIONS_TEAM2 = "avgLast5ConversionsTeam2"
AVG_LAST_5_PENALTIES_TEAM2 = "avgLast5PenaltiesTeam2"
AVG_LAST_5_DROP_GOALS_TEAM2 = "avgLast5DropGoalsTeam2"
AVG_LAST_5_TRIES_AGAINST_TEAM2 = "avgLast5TriesAgainstTeam2"
AVG_LAST_5_CONVERSIONS_AGAINST_TEAM2 = "avgLast5ConversionsAgainstTeam2"
AVG_LAST_5_PENALTIES_AGAINST_TEAM2 = "avgLast5PenaltiesAgainstTeam2"
AVG_LAST_5_DROP_GOALS_AGAINST_TEAM2 = "avgLast5DropGoalsAgainstTeam2"

WON_LAST_TEAM1 = "wonLastGameTeam1"
WON_LAST_TEAM2 = "wonLastGameTeam2"

HOME_TEAM_CODE = "team1Code"
AWAY_TEAM_CODE = "team2Code"
MONTH_CODE = "monthCode"
VENUE_CODE = "venueCode"
DAY_CODE = "dayCode"
REFEREE_CODE = "refereeCode"
SEASON_CODE = "seasonCode"
TARGET_CODE = "targetCode"
